require_relative '../components/book'
require_relative '../components/classroom'
require_relative '../components/person'
require_relative '../components/rental'
require_relative '../components/student'
require_relative '../components/teacher'
require_relative '../components/nameable'
require_relative '../user_interface/books_ui'
require_relative '../decorator/base_decorator'
require_relative '../decorator/capitalize_decorator'
require_relative '../decorator/trimmer_decorator'

require 'json'
